### ISSUE TITLE
Disney Parks Ride Wait Times Don't Work

### ISSUE THREAD

**Issue by aschi2** [astephen2/amusement#3]
Get this error when trying to access disneyland/california adventure park wait times.

`DisneyPark.pyc in _authorize(self)
    101         r = requests.post(url, data=data, headers=headers, verify=False)
    102         response = r.json()
--> 103         auth_token = response['token_type'] + ' ' + response['access_token']
    104         return auth_token
KeyError: 'token_type'`

**Comment by rambleraptor** [comment]
Hello! I haven't looked at this repo in a long, long time. Disney has inevitably changed their API to access this information. I'm probably not going to fix this due to lack of time. If you want to make a PR, I'd be happy to take it in.

Otherwise, you might want to try a different library. I'd highly recommend themeparks (https://github.com/cubehouse/themeparks) because it looks well-maintained and has a lot of cool features.

**Comment by aschi2** [comment]
Ok thanks.
